#!/bin/bash
# AXIOM Pre-commit Hook
# Generated by AXIOM Installer

# 1. Print status message
echo "🛡️ Ejecutando AXIOM Sentinel..."

# 2. Resolve repository root
REPO_ROOT=$(git rev-parse --show-toplevel)

# 3. Execute AXIOM Sentinel
# We send PYTHONPATH to ensure imports work correctly from the repo root
export PYTHONPATH="$REPO_ROOT"
python3 "$REPO_ROOT/tools/axiom/axiom_sentinel.py" "$@"
EXIT_CODE=$?

# 4. Handle Exit Codes and Display Messages
if [ $EXIT_CODE -eq 0 ]; then
    echo "✅ AXIOM: Commit aprobado"
elif [ $EXIT_CODE -eq 1 ]; then
    echo "❌ AXIOM: Commit bloqueado"
elif [ $EXIT_CODE -eq 2 ]; then
    echo "⚠️ AXIOM: Error del sistema"
else
    # Fallback for unexpected exit codes
    echo "❌ AXIOM: Fallo inesperado (Exit Code: $EXIT_CODE)"
fi

# 5. Exit with the captured code to block/allow commit
exit $EXIT_CODE
